name: Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Deploy via FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.1
        with:
          server: ${{ secrets.FTP_HOST }}     # FTP hostname (e.g., ftpupload.net)
          username: ${{ secrets.FTP_USERNAME }}   # FTP username
          password: ${{ secrets.FTP_PASSWORD }}   # FTP password
          local-dir: ./                       # The root directory of your project
          server-dir: /htdocs/                # The directory on the InfinityFree server
          exclude: |                          # Exclude unnecessary files
            .git*
            .github/
            README.md
